/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnidemo_MainActivity */

#ifndef _Included_com_example_jnidemo_MainActivity
#define _Included_com_example_jnidemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnidemo_MainActivity
 * Method:    getStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnidemo_MainActivity_getStringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jnidemo_MainActivity
 * Method:    jniStaticShowMessage
 * Signature: (Lcom/example/jnidemo/MainActivity;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_jnidemo_MainActivity_jniStaticShowMessage
  (JNIEnv *, jobject, jobject, jstring, jstring);

/*
 * Class:     com_example_jnidemo_MainActivity
 * Method:    jniShowMessage
 * Signature: (Lcom/example/jnidemo/MainActivity;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_jnidemo_MainActivity_jniShowMessage
  (JNIEnv *, jobject, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
